apiVersion: apps/v1
kind: Deployment

metadata:
  name: beginner-privacy-api

spec:
  replicas: 2

  selector:
    matchLabels:
      app: beginner-privacy-api

  template:
    metadata:
      labels:
        app: beginner-privacy-api

    spec:
      containers:
        - name: api
          image: beginner-privacy-api:latest

          ports:
            - containerPort: 8000

          env:
            - name: APP_API_KEY
              value: "demo-key"

            - name: TOKENIZATION_SECRET
              value: "demo-secret"

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 15
